sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '8585'


  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:  LTAI5tPh1UQKZJgzMM5YFNF3
    access-key-secret: BoLij5aBNeBC3lO5zUGuz8cIucg4MY
    bucket-name: web-k-delivery